name: Build touchHLE with custom Rust (Win7)

on:
  workflow_dispatch:

jobs:
  build-win7:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install 7-Zip
      run: choco install 7zip -y
      shell: powershell

    - name: Prepare Rust folder
      run: mkdir rust && cd rust && curl -L -o rust-win7.7z https://github.com/TimofeyLednev/touchHLE-win7/releases/download/rust1.88/rust-win7.7z && 7z x rust-win7.7z
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Add Rust bin to PATH
      run: echo "${{ github.workspace }}/rust/rust-win7/bin" >> $GITHUB_PATH
      shell: bash

    - name: Print PATH and confirm rustc
      run: |
        echo "PATH: $PATH"
        rustc --version
        cargo --version
      shell: bash

    - name: Clone original touchHLE
      run: git clone --recursive https://github.com/ciciplusplus/touchHLE.git
      shell: bash

    - name: Download Boost
      run: |
        curl -L -o boost.7z https://archives.boost.io/release/1.81.0/source/boost_1_81_0.7z
        7z x boost.7z -ovendor
        mv vendor/boost_1_81_0 vendor/boost
      shell: bash

    - name: Build with custom Rust
      run: cargo build --release
      working-directory: touchHLE
      shell: bash
