name: Build touchHLE with custom Rust (Win7)

on:
  workflow_dispatch:

jobs:
  build-win7:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install 7-Zip
      run: choco install 7zip
      shell: powershell

    - name: Download modified Rust for Win7
      run: |
        curl -L -o rust-win7.7z https://github.com/TimofeyLednev/touchHLE-win7/releases/download/rust1.88/rust-win7.7z
        if [ $? -ne 0 ]; then
          echo "Failed to download rust-win7.7z"
          exit 1
        fi
        ls -l rust-win7.7z
        7z x rust-win7.7z -orust-win7
        if [ $? -ne 0 ]; then
          echo "Failed to extract rust-win7.7z"
          exit 1
        fi
      shell: bash

    - name: Prepend Rust bin to PATH
      run: echo "PATH=${{ github.workspace }}/rust-win7/bin:\$PATH" >> $GITHUB_ENV
      shell: bash

    - name: Check Rust binaries location and version
      run: |
        command -v rustc
        command -v cargo
        rustc --version
        cargo --version
        echo "PATH: $PATH"
      shell: bash

    - name: Clone original touchHLE
      run: git clone --recursive https://github.com/ciciplusplus/touchHLE.git
      shell: bash

    - name: Download Boost
      run: |
        curl -L -o boost.7z https://archives.boost.io/release/1.81.0/source/boost_1_81_0.7z
        7z x boost.7z -ovendor
        mv vendor/boost_1_81_0 vendor/boost
      shell: bash

    - name: Build with custom Rust
      run: cargo build --release
      working-directory: touchHLE
      shell: bash
