name: Build touchHLE (Windows Vista SP2+ compatible)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUST_TOOLCHAIN_URL: "https://github.com/TimofeyLednev/touchHLE-win7/releases/download/Rust1.88/rust-win7.7z"
  LLVM_VERSION: "12.0.1"

jobs:
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      # 1. Полная очистка Rust
      - name: Clean Rust environment
        run: |
          Remove-Item -Path "$env:USERPROFILE\.cargo" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "$env:USERPROFILE\.rustup" -Recurse -Force -ErrorAction SilentlyContinue
          
          $cleanPath = ($env:PATH -split ';' | Where-Object {
              $_ -notmatch 'rustup|cargo|\.rustup|\.cargo'
          }) -join ';'
          echo "PATH=$cleanPath" >> $env:GITHUB_ENV
          Write-Output "Окружение Rust полностью очищено"

      # 2. Установка кастомного Rust
      - name: Install custom Rust
        run: |
          Invoke-WebRequest -Uri $env:RUST_TOOLCHAIN_URL -OutFile "rust-win7.7z"
          
          7z x rust-win7.7z -o"C:\rust-toolchain" -y
          
          $newPath = "C:\rust-toolchain\bin;$env:PATH"
          echo "C:\rust-toolchain\bin" >> $env:GITHUB_PATH
          echo "CARGO_HOME=C:\rust-toolchain" >> $env:GITHUB_ENV
          echo "RUSTUP_HOME=C:\rust-toolchain" >> $env:GITHUB_ENV
          
          Write-Output "Установка завершена. Проверяем:"
          $env:PATH = "C:\rust-toolchain\bin;$env:PATH"
          Get-Command rustc -ErrorAction Stop | Out-Null
          rustc --version
          cargo --version

      - name: Clone touchHLE
        run: |
          git clone https://github.com/touchHLE/touchHLE.git --recurse-submodules
          cd touchHLE
          git submodule update --init --recursive

      - name: Apply proc_macro patch
        working-directory: ./touchHLE
        run: |
          curl -L -o downgrade_proc_macro.patch https://raw.githubusercontent.com/TimofeyLednev/touchHLE-win7/main/downgrade_proc_macro.patch
          git apply --verbose --ignore-whitespace downgrade_proc_macro.patch

      - name: Install Boost 1.81.0
        working-directory: ./touchHLE
        shell: cmd
        run: |
          if not exist "vendor\boost" (
            echo Установка Boost 1.81.0...
            curl -L -o boost_1_81_0.7z "https://archives.boost.io/release/1.81.0/source/boost_1_81_0.7z"
            7z x boost_1_81_0.7z -ovendor
            ren vendor\boost_1_81_0 boost
            echo BOOST_ROOT=%cd%\vendor\boost >> %GITHUB_ENV%
          )
          if not exist "vendor\boost\boost\version.hpp" (
            echo Ошибка: Boost не установился правильно!
            exit 1
          )
      
      - name: Install LLVM
        shell: powershell
        run: |
          $url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ env.LLVM_VERSION }}/LLVM-${{ env.LLVM_VERSION }}-win64.exe"
          Invoke-WebRequest -Uri $url -OutFile "llvm.exe"
          Start-Process -Wait -FilePath "llvm.exe" -ArgumentList "/S"

      - name: Build
        working-directory: ./touchHLE
        run: |
          cargo build --release
          cd dev-scripts
          ./make-windows-bundle.sh ../target/release/touchHLE.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: touchHLE_Windows
          path: |
            touchHLE/touchHLE_windows_bundle/
            touchHLE/target/release/touchHLE.exe
