name: Build touchHLE (Windows 7+ compatible)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUST_TOOLCHAIN_URL: "https://github.com/TimofeyLednev/touchHLE-win7/releases/download/Rust1.88/rust-win7.7z"  
  LLVM_VERSION: "12.0.1" 

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Clone touchHLE
        shell: powershell
        run: |
          git clone https://github.com/touchHLE/touchHLE.git --recurse-submodules
          cd touchHLE
          git submodule update --init --recursive

      - name: Downgrade version proc macro2 using patch
        shell: powershell
        run: |
          cd touchHLE
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/TimofeyLednev/touchHLE-win7/main/downgrade_proc_macro.patch" -OutFile "downgrade_proc_macro.patch"
          git apply --verbose --ignore-whitespace downgrade_proc_macro.patch

      - name: Install and verify Boost
        working-directory: ./touchHLE
        shell: cmd
        run: |
          if not exist "vendor\boost" (
            echo Installing Boost 1_81_0...
            curl -L -o boost_1_81_0.7z https://archives.boost.io/release/1.81.0/source/boost_1_81_0.7z
            7z x boost_1_81_0.7z -ovendor
            ren vendor\boost_1_81_0 boost
          )
          
          echo Verifying Boost installation...
          if not exist "vendor\boost\boost\version.hpp" (
            echo ❌ Error: Boost not installed correctly!
            exit 1
          )
          echo ✅ Boost verified: version.hpp found

          echo BOOST_ROOT=%cd%\vendor\boost >> %GITHUB_ENV%

      - name: Install custom Rust
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "${{ env.RUST_TOOLCHAIN_URL }}" -OutFile "rust-win7.7z"
          7z x rust-win7.7z -o"C:\rust" -y
          echo "C:\rust\bin" >> $env:GITHUB_PATH
          rustc --version
          cargo --version

      - name: Install LLVM
        shell: powershell
        run: |
          $url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ env.LLVM_VERSION }}/LLVM-${{ env.LLVM_VERSION }}-win64.exe"
          Invoke-WebRequest -Uri $url -OutFile "llvm.exe"
          Start-Process -Wait -FilePath "llvm.exe" -ArgumentList "/S"

      - name: Build
        working-directory: ./touchHLE
        run: |
          cargo build --release
          cd dev-scripts
          ./make-windows-bundle.sh ../target/release/touchHLE.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: touchHLE_Windows
          path: |
            touchHLE/touchHLE_windows_bundle/
            touchHLE/target/release/touchHLE.exe
