name: Build touchHLE with custom Rust (Win7)

on:
  workflow_dispatch:

jobs:
  build-win7:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install 7-Zip
      run: choco install 7zip -y
      shell: powershell

    - name: Add 7-Zip to PATH
      run: echo "/c/Program Files/7-Zip" >> $GITHUB_PATH
      shell: bash

    - name: Download and extract Rust for Win7
      run: |
        curl -L -o rust-win7.7z https://github.com/TimofeyLednev/touchHLE-win7/releases/download/rust1.88/rust-win7.7z
        7z x rust-win7.7z -orust-win7
      shell: bash

    - name: Prepend Rust to PATH (correct)
      run: echo "PATH=${{ github.workspace }}/rust-win7/bin:$PATH" >> $GITHUB_ENV
      shell: bash

    - name: Confirm Rust in PATH
      run: |
        echo "Using rustc from: $(command -v rustc)"
        rustc --version
        echo "Using cargo from: $(command -v cargo)"
        cargo --version
      shell: bash

    - name: Clone original touchHLE
      run: git clone --recursive https://github.com/touchHLE/touchHLE.git
      shell: bash

    - name: Apply proc-macro version patch
      working-directory: touchHLE
      run: |
        curl -L -o downgrade_proc_macro.patch https://github.com/TimofeyLednev/touchHLE-win7/releases/download/rust1.88/downgrade_proc_macro.patch
        git apply --verbose --ignore-whitespace downgrade_proc_macro.patch
      shell: bash

    - name: Download and extract Boost
      run: |
        curl -L -o boost.7z https://archives.boost.io/release/1.81.0/source/boost_1_81_0.7z
        7z x boost.7z -ovendor
        mv vendor/boost_1_81_0 vendor/boost
      shell: bash

    - name: Force dependency versions
      working-directory: touchHLE
      run: |
        cargo update -p proc-macro2 --precise 1.0.46
        cargo update -p proc-macro-error --precise 1.0.3
        cargo update -p proc-macro-error-attr --precise 1.0.3
      shell: bash

    - name: Build with custom Rust
      run: cargo build --release
      working-directory: touchHLE
      shell: bash
