name: Build touchHLE (Windows 7+ compatible)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUST_TOOLCHAIN_URL: "https://github.com/TimofeyLednev/touchHLE-win7/releases/download/Rust1.88/rust-win7.7z"  
  LLVM_VERSION: "12.0.1" 

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      # 1. Отключаем предустановленный Rust
      - name: Disable preinstalled Rust
        shell: powershell
        run: |
          Remove-Item -Path "C:\Users\runneradmin\.cargo" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "C:\Users\runneradmin\.rustup" -Recurse -Force -ErrorAction SilentlyContinue
          echo "Предустановленный Rust удалён"

      # 2. Клонирование репозитория
      - name: Clone touchHLE
        shell: powershell
        run: |
          git clone https://github.com/touchHLE/touchHLE.git --recurse-submodules
          cd touchHLE
          git submodule update --init --recursive

      # 3. Установка КАСТОМНОГО Rust
      - name: Install custom Rust
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "${{ env.RUST_TOOLCHAIN_URL }}" -OutFile "rust-win7.7z"
          7z x rust-win7.7z -o"C:\rust" -y
          
          $newPath = "C:\rust\bin;" + $env:PATH
          echo "##[set-env name=PATH;]$newPath"
          echo "##[set-env name=CARGO_HOME;]C:\rust"
          echo "##[set-env name=RUSTUP_HOME;]C:\rust"
          
          rustc --version
          cargo --version
          echo "Используемый Rust: $(rustc --version)"

      - name: Install LLVM
        shell: powershell
        run: |
          $url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ env.LLVM_VERSION }}/LLVM-${{ env.LLVM_VERSION }}-win64.exe"
          Invoke-WebRequest -Uri $url -OutFile "llvm.exe"
          Start-Process -Wait -FilePath "llvm.exe" -ArgumentList "/S"

      - name: Build
        working-directory: ./touchHLE
        run: |
          cargo build --release
          cd dev-scripts
          ./make-windows-bundle.sh ../target/release/touchHLE.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: touchHLE_Windows
          path: |
            touchHLE/touchHLE_windows_bundle/
            touchHLE/target/release/touchHLE.exe
